bodyCamOn = false
local bodyCamDisplayOn = false
local manualDisplayOn = false
local autoDisplayOn = false
local watchingDisplayOn = false
local forceDisplayOff = false
local showOverlay = true
local doAnimation = true
local soundLevel = 0.2
local peerStreamEnabled = false
local peerStreamRemotePeerId = nil
local peerStreamPeerConfig = nil
local peerStreamCanvasId = nil
local peerStreamFps = nil
local peerStreamForceRelay = false
local peerStreamActive = false
local lastPeerId = nil
BodycamPeerId = nil
local peerStreamAutoGenerated = false
local peerStreamAnnounced = false
local TURN_REFRESH_MS = 60 * 60 * 1000
local TURN_EXPIRY_BUFFER_SECONDS = 60
local TURN_EXPIRY_BUFFER_MS = TURN_EXPIRY_BUFFER_SECONDS * 1000
local turnCache = {
    iceServers = nil,
    ttl = 0,
    expiresAt = 0
}
local turnRequestSeq = 0
local pendingTurnRequests = {}
local pendingPeerStart = nil
local recordingActive = false
local recordingConfig = {}
local recordingCooldowns = {}
local pendingRecordingStart = nil

local function nowMs()
    return GetGameTimer()
end

local function normalizeTriggerName(triggerName)
    if not triggerName then
        return nil
    end
    local normalized = tostring(triggerName):lower()
    normalized = normalized:gsub("%s+", "_")
    return normalized
end

local function isRecordingAutoTriggerEnabled(triggerName)
    local normalized = normalizeTriggerName(triggerName)
    if not normalized or type(recordingConfig.autoRecordEvents) ~= "table" then
        return false
    end
    for _, configured in ipairs(recordingConfig.autoRecordEvents) do
        if normalizeTriggerName(configured) == normalized then
            return true
        end
    end
    return false
end

local function logRecordingEvent(level, eventName, sourceType, triggerName, reason)
    TriggerServerEvent("SonoranCAD::bodycam::LogRecordingEvent", {
        level = level or "info",
        event = eventName,
        sourceType = sourceType,
        trigger = triggerName,
        reason = reason
    })
end

local function cloneTable(orig)
    if type(orig) ~= "table" then
        return orig
    end
    local copy = {}
    for k, v in pairs(orig) do
        copy[k] = v
    end
    return copy
end

local function isTurnCacheValid()
    if turnCache.iceServers == nil then
        return false
    end
    return GetGameTimer() < (turnCache.expiresAt - TURN_EXPIRY_BUFFER_MS)
end

local function requestTurnCredentials(force, cb)
    if not force and isTurnCacheValid() then
        if cb then
            cb(true, turnCache)
        end
        return
    end
    turnRequestSeq = turnRequestSeq + 1
    local requestId = turnRequestSeq
    pendingTurnRequests[requestId] = cb
    TriggerServerEvent("SonoranCAD::bodycam::RequestTurnCredentials", requestId)
end

RegisterNetEvent("SonoranCAD::bodycam::TurnCredentials", function(requestId, payload)
    local cb = pendingTurnRequests[requestId]
    pendingTurnRequests[requestId] = nil
    if payload and payload.ok and payload.iceServers then
        local ttl = tonumber(payload.ttl) or 3600
        if ttl < 60 then
            ttl = 60
        end
        turnCache.iceServers = payload.iceServers
        turnCache.ttl = ttl
        -- Use game timer to avoid os.time (not available on client).
        turnCache.expiresAt = GetGameTimer() + (ttl * 1000)
    end
    if cb then
        cb(payload and payload.ok == true, turnCache)
    end
end)
CreateThread(function()
    Config.LoadPlugin("bodycam", function(pluginConfig)
        if pluginConfig.enabled then
            doAnimation = pluginConfig.enableAnimation
            showOverlay = pluginConfig.enableOverlay
            local peerStreamConfig = pluginConfig.peerStream or {}
            peerStreamEnabled = peerStreamConfig.enabled == true
            recordingConfig = pluginConfig.recording or {}
            if type(recordingConfig.autoRecordEvents) ~= "table" then
                recordingConfig.autoRecordEvents = {}
            end
            if recordingConfig.autoRecordCooldownMs == nil then
                recordingConfig.autoRecordCooldownMs = 5000
            end
            local function GenerateRemotePeerId()
                local serverId = GetPlayerServerId(PlayerId())
                local seed = GetGameTimer() + (serverId * 1000)
                math.randomseed(seed)
                local rand = math.random(10000, 99999)
                return ('bodycam-%s-%s'):format(serverId, rand)
            end

            peerStreamRemotePeerId = peerStreamConfig.remotePeerId
            if peerStreamRemotePeerId == "" then
                peerStreamRemotePeerId = nil
            end
            if not peerStreamRemotePeerId then
                peerStreamRemotePeerId = GenerateRemotePeerId()
                peerStreamAutoGenerated = true
            end
            peerStreamPeerConfig = peerStreamConfig.peer
            peerStreamCanvasId = peerStreamConfig.canvasId
            peerStreamFps = peerStreamConfig.fps
            peerStreamForceRelay = peerStreamConfig.forceRelay == true
            if peerStreamEnabled then
                CreateThread(function()
                    while true do
                        Wait(TURN_REFRESH_MS)
                        if peerStreamEnabled then
                            requestTurnCredentials(true)
                        end
                    end
                end)
            end

            function IsWearingBodycam()
                local ped = PlayerPedId()
                local pedModel = GetEntityModel(ped)
                if not pluginConfig.clothing or #pluginConfig.clothing == 0 then
                    return true
                end
                for _, item in ipairs(pluginConfig.clothing) do
                    if not item.ped or pedModel == GetHashKey(item.ped) then
                        if item.component and item.drawable then
                            local compDrawable = GetPedDrawableVariation(ped, item.component)
                            if compDrawable == item.drawable then
                                if item.textures then
                                    local compTexture = GetPedTextureVariation(ped, item.component)
                                    for _, tex in ipairs(item.textures) do
                                        if compTexture == tex then
                                            return true
                                        end
                                    end
                                else
                                    return true
                                end
                            end
                        elseif item.component then
                            return true
                        elseif item.ped then
                            return true
                        end
                    end
                end
                return false
            end

            local function shouldDisplayBodycam()
                if forceDisplayOff then
                    return false
                end
                return manualDisplayOn or autoDisplayOn or watchingDisplayOn
            end

            local function applyDisplayState()
                local nextDisplay = shouldDisplayBodycam()
                if nextDisplay == bodyCamDisplayOn then
                    return
                end
                bodyCamDisplayOn = nextDisplay
                if bodyCamDisplayOn then
                    if showOverlay then
                        SendNUIMessage({
                            type = 'bodycamOverlay',
                            visible = true,
                            location = pluginConfig.overlayLocation
                        })
                    end
                else
                    SendNUIMessage({
                        type = 'bodycamOverlay',
                        visible = false,
                        location = pluginConfig.overlayLocation
                    })
                end
            end

            local function getRecordingMetadata()
                return {}
            end

            local function canExternalRecordingControl(sourceType)
                if not forceDisplayOff then
                    return true
                end
                if sourceType == 'manual' and recordingConfig.allowManualRecordingDuringPrivacyOverride ~= false then
                    return true
                end
                if recordingConfig.blockRemoteRecordingDuringPrivacyOverride == false and sourceType == 'remote' then
                    return true
                end
                return false
            end

            local function sendRecordingControl(action, sourceType, triggerName, reason)
                sourceType = sourceType or 'manual'
                local normalizedTrigger = normalizeTriggerName(triggerName)
                if action == 'start' then
                    if recordingActive then
                        if sourceType == 'manual' then
                            TriggerEvent('chat:addMessage', {
                                args = { 'Sonoran Bodycam', 'Recording is already active.' }
                            })
                        end
                        return
                    end
                    if not canExternalRecordingControl(sourceType) then
                        logRecordingEvent('warn', 'recording_blocked', sourceType, normalizedTrigger, 'privacy_override')
                        if sourceType == 'manual' then
                            TriggerEvent('chat:addMessage', {
                                args = { 'Sonoran Bodycam', 'Recording blocked by privacy override.' }
                            })
                        end
                        return
                    end
                    if not bodyCamOn then
                        if sourceType == 'manual' then
                            pendingRecordingStart = {
                                action = action,
                                sourceType = sourceType,
                                trigger = normalizedTrigger,
                                reason = reason
                            }
                            if not bodyCamDisplayOn then
                                TriggerServerEvent('SonoranCAD::bodycam::RequestToggle', true, true)
                            else
                                StartPeerStream()
                            end
                        end
                        return
                    end
                    logRecordingEvent('info', 'recording_start', sourceType, normalizedTrigger, reason)
                else
                    if not recordingActive then
                        if sourceType == 'manual' then
                            TriggerEvent('chat:addMessage', {
                                args = { 'Sonoran Bodycam', 'No recording is currently active.' }
                            })
                        end
                        return
                    end
                end

                SendNUIMessage({
                    type = 'bodycamRecordingControl',
                    action = action,
                    sourceType = sourceType,
                    trigger = normalizedTrigger,
                    reason = reason,
                    config = recordingConfig,
                    metadata = getRecordingMetadata()
                })
            end

            local function triggerAutoRecording(triggerName)
                local normalizedTrigger = normalizeTriggerName(triggerName)
                if not isRecordingAutoTriggerEnabled(normalizedTrigger) then
                    return
                end
                local cooldownMs = tonumber(recordingConfig.autoRecordCooldownMs) or 5000
                local currentTime = nowMs()
                if recordingCooldowns[normalizedTrigger] and currentTime - recordingCooldowns[normalizedTrigger] < cooldownMs then
                    return
                end
                recordingCooldowns[normalizedTrigger] = currentTime
                sendRecordingControl('start', 'auto', normalizedTrigger, 'auto_trigger')
            end

            local function toggleManualRecording()
                if recordingActive then
                    sendRecordingControl('stop', 'manual', 'manual', 'manual_toggle')
                else
                    sendRecordingControl('start', 'manual', 'manual', 'manual_toggle')
                end
            end

            local function buildPeerConfig(iceServers)
                local config = nil
                if type(peerStreamPeerConfig) == "table" then
                    config = cloneTable(peerStreamPeerConfig)
                else
                    config = {}
                end
                if type(config) ~= "table" then
                    config = {}
                end
                if type(config.config) ~= "table" then
                    config.config = {}
                end
                if peerStreamForceRelay then
                    config.config.iceTransportPolicy = "relay"
                end
                if type(iceServers) == "table" and #iceServers > 0 then
                    config.config.iceServers = iceServers
                elseif type(config.config.iceServers) ~= "table" or #config.config.iceServers == 0 then
                    config.config.iceServers = {
                        { urls = { "stun:stun.l.google.com:19302" } }
                    }
                end
                return config
            end

            local function StartPeerStream()
                if not peerStreamEnabled or peerStreamActive then
                    if not peerStreamEnabled then
                        debugLog('Bodycam peer stream is disabled in config.')
                    end
                    return
                end

                peerStreamActive = true
                bodyCamOn = true
                debugLog(('Bodycam peer stream starting. remotePeerId=%s'):format(tostring(peerStreamRemotePeerId)))
                if peerStreamAutoGenerated and not peerStreamAnnounced then
                    peerStreamAnnounced = true
                end
                local startPayload = {
                    type = 'bodycamStream',
                    enabled = true,
                    remotePeerId = peerStreamRemotePeerId,
                    canvasId = peerStreamCanvasId,
                    fps = peerStreamFps
                }
                pendingPeerStart = startPayload
                requestTurnCredentials(false, function(_, cache)
                    if pendingPeerStart ~= startPayload then
                        return
                    end
                    pendingPeerStart = nil
                    local iceServers = cache and cache.iceServers or nil
                    startPayload.peerConfig = buildPeerConfig(iceServers)
                    SendNUIMessage(startPayload)
                    if pendingRecordingStart and pendingRecordingStart.action == 'start' then
                        local pending = pendingRecordingStart
                        pendingRecordingStart = nil
                        SetTimeout(750, function()
                            if bodyCamOn then
                                sendRecordingControl('start', pending.sourceType, pending.trigger, pending.reason)
                            end
                        end)
                    end
                end)
            end

            local function StopPeerStream()
                if not peerStreamEnabled or not peerStreamActive then
                    return
                end
                peerStreamActive = false
                bodyCamOn = false
                pendingRecordingStart = nil
                pendingPeerStart = nil
                lastPeerId = nil
                BodycamPeerId = nil
                SendNUIMessage({
                    type = 'bodycamStream',
                    enabled = false
                })
            end

            RegisterNUICallback('bodycamPeerId', function(data, cb)
                if data and data.id and data.id ~= lastPeerId then
                    lastPeerId = data.id
                    BodycamPeerId = data.id
                    debugLog(('Bodycam peer stream ID: %s'):format(data.id))
                end
                cb({ ok = true })
            end)

            RegisterNUICallback('bodycamWatching', function(data, cb)
                local watching = data and data.watching == true
                if watchingDisplayOn ~= watching then
                    watchingDisplayOn = watching
                    applyDisplayState()
                end
                cb({ ok = true })
            end)

            RegisterNUICallback('bodycamRecordingState', function(data, cb)
                local state = data and data.state or nil
                if state == 'started' then
                    recordingActive = true
                    if recordingConfig.enableRecordingSfx ~= false then
                        SendNUIMessage({
                            type = 'playSound',
                            transactionFile = recordingConfig.recordingStartSfx or 'sounds/beeps.mp3',
                            transactionVolume = soundLevel
                        })
                    end
                    TriggerEvent('chat:addMessage', {
                        args = { 'Sonoran Bodycam', 'Recording started.' }
                    })
                elseif state == 'stopped' then
                    recordingActive = false
                    if recordingConfig.enableRecordingSfx ~= false then
                        SendNUIMessage({
                            type = 'playSound',
                            transactionFile = recordingConfig.recordingStopSfx or 'sounds/beep_off.mp3',
                            transactionVolume = soundLevel
                        })
                    end
                    TriggerEvent('chat:addMessage', {
                        args = { 'Sonoran Bodycam', 'Recording stopped. Uploading clip...' }
                    })
                elseif state == 'failed' then
                    recordingActive = false
                    TriggerEvent('chat:addMessage', {
                        args = { 'Sonoran Bodycam', ('Recording failed: %s'):format(tostring(data.reason or 'unknown')) }
                    })
                    logRecordingEvent('warn', 'recording_failed', data.sourceType, data.trigger, data.reason)
                end
                cb({ ok = true })
            end)

            RegisterNUICallback('bodycamRecordingUpload', function(data, cb)
                TriggerServerEvent('SonoranCAD::bodycam::UploadRecording', data)
                cb({ ok = true })
            end)

            function PlayBeepSound()
                if pluginConfig.beepType == 'native' then
                    local coord = GetEntityCoords(GetPlayerPed(PlayerId()))
                    PlaySoundFromCoord(-1, 'Beep_Red', coord.x, coord.y, coord.z,
                        'DLC_HEIST_HACKING_SNAKE_SOUNDS', false, 0, false)
                else
                    SendNUIMessage({
                        type = 'playSound',
                        transactionFile = 'sounds/beeps.mp3',
                        transactionVolume = soundLevel
                    })
                end
            end

            function PlayOffBeep()
                if pluginConfig.beepType == 'native' then
                    local coord = GetEntityCoords(GetPlayerPed(PlayerId()))
                    PlaySoundFromCoord(-1, 'Beep_Green', coord.x, coord.y, coord.z,
                        'DLC_HEIST_HACKING_SNAKE_SOUNDS', false, 0, false)
                else
                    SendNUIMessage({
                        type = 'playSound',
                        transactionFile = 'sounds/beep_off.mp3',
                        transactionVolume = soundLevel
                    })
                end
            end

            AddEventHandler('playerSpawned', function()
                TriggerServerEvent('SonoranCAD::bodycam::Request')
            end)

            TriggerEvent('chat:addSuggestion', '/' .. pluginConfig.command, '',
                { { name = "[sound|anim|overlay|forceoff]", help = "Subcommand" } })
            RegisterPlayerCommandHelp("bodycam", pluginConfig.command, "Manage Sonoran bodycam display options.", "[sound|anim|overlay|forceoff]")
            RegisterCommand('SonoranCAD::bodycam::Keybind', function()
                local turnOn = not bodyCamDisplayOn
                TriggerServerEvent('SonoranCAD::bodycam::RequestToggle', true, turnOn)
            end, false)
            RegisterKeyMapping('SonoranCAD::bodycam::Keybind', "Toggle BodyCam", "keyboard", pluginConfig.defaultKeybind)
            if recordingConfig.commands and recordingConfig.commands.toggleRecording and
                recordingConfig.commands.toggleRecording ~= '' then
                RegisterCommand(recordingConfig.commands.toggleRecording, function()
                    toggleManualRecording()
                end, false)
                TriggerEvent('chat:addSuggestion', '/' .. recordingConfig.commands.toggleRecording,
                    'Toggle local bodycam recording')
                RegisterPlayerCommandHelp("bodycam", recordingConfig.commands.toggleRecording, "Toggle local bodycam recording.")
            end
            RegisterCommand('SonoranCAD::bodycam::RecordingKeybind', function()
                toggleManualRecording()
            end, false)
            RegisterKeyMapping('SonoranCAD::bodycam::RecordingKeybind', "Toggle BodyCam Recording", "keyboard",
                (recordingConfig.keybinds and recordingConfig.keybinds.toggleRecording) or '')
            CreateThread(function()
                while pluginConfig.autoEnableWithWeapons do
                    Wait(200)
                    local ped = PlayerPedId()
                    local weapon = GetSelectedPedWeapon(ped)
                    if not autoDisplayOn and pluginConfig.weapons then
                        for _, weaponName in ipairs(pluginConfig.weapons) do
                            if weapon == GetHashKey(weaponName) then
                                if not forceDisplayOff then
                                    TriggerServerEvent('SonoranCAD::bodycam::RequestToggle', false, true)
                                end
                                triggerAutoRecording('weapon_draw')
                                break
                            end
                        end
                    end
                end
            end)

            CreateThread(function()
                while pluginConfig.autoEnableWithLights do
                    Wait(200)
                    local ped = PlayerPedId()
                    local veh = GetVehiclePedIsIn(ped, false)
                    -- Only check if player is in a vehicle and is the driver
                    if veh ~= 0 and GetPedInVehicleSeat(veh, -1) == ped and GetVehicleClass(veh) == 18 then
                        if IsVehicleSirenOn(veh) then
                            if not autoDisplayOn then
                                if not forceDisplayOff then
                                    TriggerServerEvent('SonoranCAD::bodycam::RequestToggle', false, true)
                                end
                            end
                        end
                    end
                end
            end)

            CreateThread(function()
                while true do
                    Wait(1)
                    if pluginConfig.enableBeeps then
                        if bodyCamDisplayOn then
                            PlayBeepSound()
                            if pluginConfig.enablePadShake then
                                SetPadShake(0, 300, 255)
                                Wait(500)
                                SetPadShake(0, 300, 255)
                            end
                            TriggerServerEvent('SonoranCAD::bodycam::RequestSound')
                            Wait(pluginConfig.beepFrequency)
                        end
                    end
                end
            end)

            RegisterNetEvent('SonoranCAD::bodycam::GiveSound', function(serverId, serverCoords)
                if GetPlayerFromServerId(serverId) ~= PlayerId() and GetDistanceBetweenCoords(GetEntityCoords(GetPlayerPed(PlayerId())), serverCoords, true) < pluginConfig.beepRange then
                    PlayBeepSound()
                end
            end)

            RegisterNetEvent('SonoranCAD::bodycam::AutoRecordTrigger', function(triggerName)
                triggerAutoRecording(triggerName)
            end)

            RegisterNetEvent('SonoranCAD::bodycam::UploadResult', function(result)
                if result and result.ok then
                    TriggerEvent('chat:addMessage', {
                        args = { 'Sonoran Bodycam', 'Recording uploaded to CAD.' }
                    })
                else
                    TriggerEvent('chat:addMessage', {
                        args = { 'Sonoran Bodycam', ('Recording upload failed: %s'):format(tostring(result and result.reason or 'unknown')) }
                    })
                end
            end)

            RegisterNetEvent('SonoranCAD::bodycam::Init', function(isReady, apiVersion)
                if isReady == 0 then
                    CreateThread(function()
                        debugLog('Bodycam not ready, retrying in 10s')
                        Wait(10000)
                        TriggerServerEvent('SonoranCAD::bodycam::Request')
                    end)
                    return
                end
                if apiVersion ~= -1 then
                    Config.apiVersion = apiVersion
                end

                StartPeerStream()
                applyDisplayState()

                RegisterNetEvent('SonoranCAD::bodycam::Toggle', function(manualActivation, toggle, forceOff)
                    if forceDisplayOff and not manualActivation then
                        return
                    end
                    if not IsWearingBodycam() then
                        if manualActivation then
                            TriggerEvent('chat:addMessage',
                                { args = { 'Sonoran Bodycam', 'You must be wearing a bodycam to activate it.' } })
                            return
                        end
                    end

                    if manualActivation and not toggle and watchingDisplayOn and not forceOff then
                        TriggerEvent('chat:addMessage',
                            { args = { 'Sonoran Bodycam', 'Bodycam is being watched and cannot be turned off.' } })
                        return
                    end

                    if forceOff then
                        forceDisplayOff = true
                    elseif manualActivation and toggle then
                        forceDisplayOff = false
                    end

                    if manualActivation and doAnimation then
                        local ped = PlayerPedId()
                        RequestAnimDict("clothingtie")
                        while not HasAnimDictLoaded("clothingtie") do
                            Wait(10)
                        end
                        TaskPlayAnim(ped, "clothingtie", "outro", 8.0, 2.0, 1880, 51, 2.0, false, false, false)
                        Wait(1880)
                    end

                    local wasDisplayOn = bodyCamDisplayOn

                    if manualActivation then
                        if toggle then
                            manualDisplayOn = true
                        else
                            manualDisplayOn = false
                            autoDisplayOn = false
                        end
                    else
                        if toggle then
                            autoDisplayOn = true
                        else
                            autoDisplayOn = false
                        end
                    end

                    applyDisplayState()
                    if toggle and not forceDisplayOff then
                        StartPeerStream()
                    elseif forceOff then
                        StopPeerStream()
                    end

                    if wasDisplayOn ~= bodyCamDisplayOn then
                        if bodyCamDisplayOn then
                            TriggerEvent('chat:addMessage',
                                { args = { 'Sonoran Bodycam', 'Bodycam enabled' } })
                            PlayBeepSound()
                            if pendingRecordingStart and pendingRecordingStart.action == 'start' then
                                local pending = pendingRecordingStart
                                pendingRecordingStart = nil
                                SetTimeout(750, function()
                                    if bodyCamOn then
                                        sendRecordingControl('start', pending.sourceType, pending.trigger,
                                            pending.reason)
                                    end
                                end)
                            end
                        else
                            TriggerEvent('chat:addMessage',
                                { args = { 'Sonoran Bodycam', 'Bodycam disabled' } })
                            PlayOffBeep()
                            if pluginConfig.enablePadShake then
                                SetPadShake(0, 2000, 200)
                            end
                        end
                    end
                end)
                RegisterNetEvent('SonoranCAD::bodycam::CommandToggle', function()
                    TriggerServerEvent('SonoranCAD::bodycam::RequestToggle', true, not bodyCamDisplayOn)
                end)
                RegisterNetEvent('SonoranCAD::bodycam::SetSoundLevel', function(level)
                    if level then
                        level = tonumber(level)
                        if not level or level <= 0 or level > 1 then
                            errorLog('Sound level must be a number greater than 0 and less then 1.0 percent.')
                            TriggerEvent('chat:addMessage', {
                                args = { 'Sonoran Bodycam', 'Sound level must be a number greater than 0 and less then 1.0 percent.' }
                            })
                            return
                        end
                        soundLevel = tonumber(level)
                        TriggerEvent('chat:addMessage',
                            { args = { 'Sonoran Bodycam', ('Sound level set to %s'):format(soundLevel) } })
                    else
                        TriggerEvent('chat:addMessage', {
                            args = { 'Sonoran Bodycam', ('Current sound level is %s'):format((soundLevel)) }
                        })
                    end
                end)
                RegisterNetEvent('SonoranCAD::bodycam::ToggleAnimation', function()
                    if doAnimation then
                        doAnimation = false
                    else
                        doAnimation = true
                    end
                    TriggerEvent('chat:addMessage',
                        { args = { 'Sonoran Bodycam', ('Animations set to %s'):format(doAnimation) } })
                end)
                RegisterNetEvent('SonoranCAD::bodycam::ToggleOverlay', function()
                    if showOverlay then
                        showOverlay = false
                    else
                        showOverlay = true
                    end
                    if bodyCamDisplayOn then
                        SendNUIMessage({
                            type = 'bodycamOverlay',
                            visible = showOverlay,
                            location = pluginConfig.overlayLocation
                        })
                    end
                    TriggerEvent('chat:addMessage',
                        { args = { 'Sonoran Bodycam', ('Overlay set to %s'):format(showOverlay) } })
                end)
            end)
        end
    end)
end)
