bodyCamOn = false
local bodyCamDisplayOn = false
local manualDisplayOn = false
local autoDisplayOn = false
local watchingDisplayOn = false
local showOverlay = true
local doAnimation = true
screenshotFrequency = 2000
local soundLevel = 0.2
local peerStreamEnabled = false
local peerStreamRemotePeerId = nil
local peerStreamPeerConfig = nil
local peerStreamCanvasId = nil
local peerStreamFps = nil
local peerStreamForceRelay = false
local peerStreamActive = false
local lastPeerId = nil
BodycamPeerId = nil
local peerStreamAutoGenerated = false
local peerStreamAnnounced = false
local TURN_REFRESH_MS = 60 * 60 * 1000
local TURN_EXPIRY_BUFFER_SECONDS = 60
local turnCache = {
    iceServers = nil,
    ttl = 0,
    expiresAt = 0
}
local turnRequestSeq = 0
local pendingTurnRequests = {}
local pendingPeerStart = nil

local function cloneTable(orig)
    if type(orig) ~= "table" then
        return orig
    end
    local copy = {}
    for k, v in pairs(orig) do
        copy[k] = v
    end
    return copy
end

local function isTurnCacheValid()
    if turnCache.iceServers == nil then
        return false
    end
    return os.time() < (turnCache.expiresAt - TURN_EXPIRY_BUFFER_SECONDS)
end

local function requestTurnCredentials(force, cb)
    if not force and isTurnCacheValid() then
        if cb then
            cb(true, turnCache)
        end
        return
    end
    turnRequestSeq = turnRequestSeq + 1
    local requestId = turnRequestSeq
    pendingTurnRequests[requestId] = cb
    TriggerServerEvent("SonoranCAD::bodycam::RequestTurnCredentials", requestId)
end

RegisterNetEvent("SonoranCAD::bodycam::TurnCredentials", function(requestId, payload)
    local cb = pendingTurnRequests[requestId]
    pendingTurnRequests[requestId] = nil
    if payload and payload.ok and payload.iceServers then
        local ttl = tonumber(payload.ttl) or 3600
        if ttl < 60 then
            ttl = 60
        end
        turnCache.iceServers = payload.iceServers
        turnCache.ttl = ttl
        turnCache.expiresAt = payload.expiresAt or (os.time() + ttl)
    end
    if cb then
        cb(payload and payload.ok == true, turnCache)
    end
end)
CreateThread(function()
    Config.LoadPlugin("bodycam", function(pluginConfig)
        if pluginConfig.enabled then
            doAnimation = pluginConfig.enableAnimation
            showOverlay = pluginConfig.enableOverlay
            screenshotFrequency = pluginConfig.screenshotFrequency
            local peerStreamConfig = pluginConfig.peerStream or {}
            peerStreamEnabled = peerStreamConfig.enabled == true
            local function GenerateRemotePeerId()
                local serverId = GetPlayerServerId(PlayerId())
                local seed = GetGameTimer() + (serverId * 1000)
                math.randomseed(seed)
                local rand = math.random(10000, 99999)
                return ('bodycam-%s-%s'):format(serverId, rand)
            end

            peerStreamRemotePeerId = peerStreamConfig.remotePeerId
            if peerStreamRemotePeerId == "" then
                peerStreamRemotePeerId = nil
            end
            if not peerStreamRemotePeerId then
                peerStreamRemotePeerId = GenerateRemotePeerId()
                peerStreamAutoGenerated = true
            end
            peerStreamPeerConfig = peerStreamConfig.peer
            peerStreamCanvasId = peerStreamConfig.canvasId
            peerStreamFps = peerStreamConfig.fps
            peerStreamForceRelay = peerStreamConfig.forceRelay == true
            if peerStreamEnabled then
                CreateThread(function()
                    while true do
                        Wait(TURN_REFRESH_MS)
                        if peerStreamEnabled then
                            requestTurnCredentials(true)
                        end
                    end
                end)
            end

            function IsWearingBodycam()
                local ped = PlayerPedId()
                local pedModel = GetEntityModel(ped)
                if not pluginConfig.clothing or #pluginConfig.clothing == 0 then
                    return true
                end
                for _, item in ipairs(pluginConfig.clothing) do
                    if not item.ped or pedModel == GetHashKey(item.ped) then
                        if item.component and item.drawable then
                            local compDrawable = GetPedDrawableVariation(ped, item.component)
                            if compDrawable == item.drawable then
                                if item.textures then
                                    local compTexture = GetPedTextureVariation(ped, item.component)
                                    for _, tex in ipairs(item.textures) do
                                        if compTexture == tex then
                                            return true
                                        end
                                    end
                                else
                                    return true
                                end
                            end
                        elseif item.component then
                            return true
                        elseif item.ped then
                            return true
                        end
                    end
                end
                return false
            end

            local function shouldDisplayBodycam()
                return manualDisplayOn or autoDisplayOn or watchingDisplayOn
            end

            local function applyDisplayState()
                local nextDisplay = shouldDisplayBodycam()
                if nextDisplay == bodyCamDisplayOn then
                    return
                end
                bodyCamDisplayOn = nextDisplay
                if bodyCamDisplayOn then
                    if showOverlay then
                        SendNUIMessage({
                            type = 'bodycamOverlay',
                            visible = true,
                            location = pluginConfig.overlayLocation
                        })
                    end
                else
                    SendNUIMessage({
                        type = 'bodycamOverlay',
                        visible = false,
                        location = pluginConfig.overlayLocation
                    })
                end
            end

            local function buildPeerConfig(iceServers)
                local config = nil
                if type(peerStreamPeerConfig) == "table" then
                    config = cloneTable(peerStreamPeerConfig)
                else
                    config = {}
                end
                if type(config) ~= "table" then
                    config = {}
                end
                if type(config.config) ~= "table" then
                    config.config = {}
                end
                if peerStreamForceRelay then
                    config.config.iceTransportPolicy = "relay"
                end
                if type(iceServers) == "table" and #iceServers > 0 then
                    config.config.iceServers = iceServers
                elseif type(config.config.iceServers) ~= "table" or #config.config.iceServers == 0 then
                    config.config.iceServers = {
                        { urls = { "stun:stun.l.google.com:19302" } }
                    }
                end
                return config
            end

            local function StartPeerStream()
                if not peerStreamEnabled or peerStreamActive then
                    if not peerStreamEnabled then
                        debugLog('Bodycam peer stream is disabled in config.')
                    end
                    return
                end

                peerStreamActive = true
                bodyCamOn = true
                debugLog(('Bodycam peer stream starting. remotePeerId=%s'):format(tostring(peerStreamRemotePeerId)))
                if peerStreamAutoGenerated and not peerStreamAnnounced then
                    peerStreamAnnounced = true
                end
                local startPayload = {
                    type = 'bodycamStream',
                    enabled = true,
                    remotePeerId = peerStreamRemotePeerId,
                    canvasId = peerStreamCanvasId,
                    fps = peerStreamFps
                }
                pendingPeerStart = startPayload
                requestTurnCredentials(false, function(_, cache)
                    if pendingPeerStart ~= startPayload then
                        return
                    end
                    pendingPeerStart = nil
                    local iceServers = cache and cache.iceServers or nil
                    startPayload.peerConfig = buildPeerConfig(iceServers)
                    SendNUIMessage(startPayload)
                end)
            end

            local function StopPeerStream()
                if not peerStreamEnabled or not peerStreamActive then
                    return
                end
                peerStreamActive = false
                bodyCamOn = false
                pendingPeerStart = nil
                lastPeerId = nil
                BodycamPeerId = nil
                SendNUIMessage({
                    type = 'bodycamStream',
                    enabled = false
                })
            end

            RegisterNUICallback('bodycamPeerId', function(data, cb)
                if data and data.id and data.id ~= lastPeerId then
                    lastPeerId = data.id
                    BodycamPeerId = data.id
                    debugLog(('Bodycam peer stream ID: %s'):format(data.id))
                end
                cb({ ok = true })
            end)

            RegisterNUICallback('bodycamWatching', function(data, cb)
                local watching = data and data.watching == true
                if watchingDisplayOn ~= watching then
                    watchingDisplayOn = watching
                    applyDisplayState()
                end
                cb({ ok = true })
            end)

            function PlayBeepSound()
                if pluginConfig.beepType == 'native' then
                    local coord = GetEntityCoords(GetPlayerPed(PlayerId()))
                    PlaySoundFromCoord(-1, 'Beep_Red', coord.x, coord.y, coord.z,
                        'DLC_HEIST_HACKING_SNAKE_SOUNDS', false, 0, false)
                else
                    SendNUIMessage({
                        type = 'playSound',
                        transactionFile = 'sounds/beeps.mp3',
                        transactionVolume = soundLevel
                    })
                end
            end

            function PlayOffBeep()
                if pluginConfig.beepType == 'native' then
                    local coord = GetEntityCoords(GetPlayerPed(PlayerId()))
                    PlaySoundFromCoord(-1, 'Beep_Green', coord.x, coord.y, coord.z,
                        'DLC_HEIST_HACKING_SNAKE_SOUNDS', false, 0, false)
                else
                    SendNUIMessage({
                        type = 'playSound',
                        transactionFile = 'sounds/beep_off.mp3',
                        transactionVolume = soundLevel
                    })
                end
            end

            AddEventHandler('playerSpawned', function()
                TriggerServerEvent('SonoranCAD::bodycam::Request')
            end)

            TriggerEvent('chat:addSuggestion', '/' .. pluginConfig.command, '',
                { { name = "[freq|sound|anim|overlay]", help = "Subcommand" } })
            RegisterCommand('SonoranCAD::bodycam::Keybind', function()
                local turnOn = not bodyCamDisplayOn
                TriggerServerEvent('SonoranCAD::bodycam::RequestToggle', true, turnOn)
            end, false)
            RegisterKeyMapping('SonoranCAD::bodycam::Keybind', "Toggle BodyCam", "keyboard", pluginConfig.defaultKeybind)
            CreateThread(function()
                while pluginConfig.autoEnableWithWeapons do
                    Wait(200)
                    local ped = PlayerPedId()
                    local weapon = GetSelectedPedWeapon(ped)
                    if not autoDisplayOn and pluginConfig.weapons then
                        for _, weaponName in ipairs(pluginConfig.weapons) do
                            if weapon == GetHashKey(weaponName) then
                                TriggerServerEvent('SonoranCAD::bodycam::RequestToggle', false, true)
                                break
                            end
                        end
                    end
                end
            end)

            CreateThread(function()
                while pluginConfig.autoEnableWithLights do
                    Wait(200)
                    local ped = PlayerPedId()
                    local veh = GetVehiclePedIsIn(ped, false)
                    -- Only check if player is in a vehicle and is the driver
                    if veh ~= 0 and GetPedInVehicleSeat(veh, -1) == ped and GetVehicleClass(veh) == 18 then
                        if IsVehicleSirenOn(veh) then
                            if not autoDisplayOn then
                                TriggerServerEvent('SonoranCAD::bodycam::RequestToggle', false, true)
                            end
                        end
                    end
                end
            end)

            CreateThread(function()
                while true do
                    Wait(1)
                    if pluginConfig.enableBeeps then
                        if bodyCamDisplayOn then
                            PlayBeepSound()
                            if pluginConfig.enablePadShake then
                                SetPadShake(0, 300, 255)
                                Wait(500)
                                SetPadShake(0, 300, 255)
                            end
                            TriggerServerEvent('SonoranCAD::bodycam::RequestSound')
                            Wait(pluginConfig.beepFrequency)
                        end
                    end
                end
            end)

            RegisterNetEvent('SonoranCAD::bodycam::GiveSound', function(serverId, serverCoords)
                if GetPlayerFromServerId(serverId) ~= PlayerId() and GetDistanceBetweenCoords(GetEntityCoords(GetPlayerPed(PlayerId())), serverCoords, true) < pluginConfig.beepRange then
                    PlayBeepSound()
                end
            end)

            RegisterNetEvent('SonoranCAD::bodycam::Init', function(isReady, apiVersion)
                if isReady == 0 then
                    CreateThread(function()
                        debugLog('Bodycam not ready, retrying in 10s')
                        Wait(10000)
                        TriggerServerEvent('SonoranCAD::bodycam::Request')
                    end)
                    return
                end
                if apiVersion ~= -1 then
                    Config.apiVersion = apiVersion
                end

                StartPeerStream()
                applyDisplayState()

                RegisterNetEvent('SonoranCAD::bodycam::Toggle', function(manualActivation, toggle)
                    if not IsWearingBodycam() then
                        if manualActivation then
                            TriggerEvent('chat:addMessage',
                                { args = { 'Sonoran Bodycam', 'You must be wearing a bodycam to activate it.' } })
                            return
                        end
                    end

                    if manualActivation and not toggle and watchingDisplayOn then
                        TriggerEvent('chat:addMessage',
                            { args = { 'Sonoran Bodycam', 'Bodycam is being watched and cannot be turned off.' } })
                        return
                    end

                    if manualActivation and doAnimation then
                        local ped = PlayerPedId()
                        RequestAnimDict("clothingtie")
                        while not HasAnimDictLoaded("clothingtie") do
                            Wait(10)
                        end
                        TaskPlayAnim(ped, "clothingtie", "outro", 8.0, 2.0, 1880, 51, 2.0, false, false, false)
                        Wait(1880)
                    end

                    local wasDisplayOn = bodyCamDisplayOn

                    if manualActivation then
                        if toggle then
                            manualDisplayOn = true
                        else
                            manualDisplayOn = false
                            autoDisplayOn = false
                        end
                    else
                        if toggle then
                            autoDisplayOn = true
                        else
                            autoDisplayOn = false
                        end
                    end

                    applyDisplayState()
                    if toggle then
                        StartPeerStream()
                    end

                    if wasDisplayOn ~= bodyCamDisplayOn then
                        if bodyCamDisplayOn then
                            TriggerEvent('chat:addMessage',
                                { args = { 'Sonoran Bodycam', 'Bodycam enabled' } })
                            PlayBeepSound()
                        else
                            TriggerEvent('chat:addMessage',
                                { args = { 'Sonoran Bodycam', 'Bodycam disabled' } })
                            PlayOffBeep()
                            if pluginConfig.enablePadShake then
                                SetPadShake(0, 2000, 200)
                            end
                        end
                    end
                end)
                RegisterNetEvent('SonoranCAD::bodycam::SetScreenshotFrequency', function(frequency)
                    if frequency then
                        frequency = tonumber(frequency)
                        if not frequency or frequency <= 0 or frequency > 10 then
                            errorLog('Screenshot Frequency must be a number greater than 0 and less then 10 seconds.')
                            TriggerEvent('chat:addMessage', {
                                args = { 'Sonoran Bodycam', 'Screenshot Frequency must be a number greater than 0 and less then 10 seconds.' }
                            })
                            return
                        end

                        screenshotFrequency = (tonumber(frequency) * 1000)
                        TriggerEvent('chat:addMessage',
                            { args = { 'Sonoran Bodycam', ('Screenshot Frequency set to %s'):format((screenshotFrequency / 1000)) } })
                    else
                        TriggerEvent('chat:addMessage', {
                            args = { 'Sonoran Bodycam', ('Current screenshot frequency is %s'):format((screenshotFrequency / 1000)) }
                        })
                    end
                end)
                RegisterNetEvent('SonoranCAD::bodycam::CommandToggle', function()
                    TriggerServerEvent('SonoranCAD::bodycam::RequestToggle', true, not bodyCamDisplayOn)
                end)
                RegisterNetEvent('SonoranCAD::bodycam::SetSoundLevel', function(level)
                    if level then
                        level = tonumber(level)
                        if not level or level <= 0 or level > 1 then
                            errorLog('Sound level must be a number greater than 0 and less then 1.0 percent.')
                            TriggerEvent('chat:addMessage', {
                                args = { 'Sonoran Bodycam', 'Sound level must be a number greater than 0 and less then 1.0 percent.' }
                            })
                            return
                        end
                        soundLevel = tonumber(level)
                        TriggerEvent('chat:addMessage',
                            { args = { 'Sonoran Bodycam', ('Sound level set to %s'):format(soundLevel) } })
                    else
                        TriggerEvent('chat:addMessage', {
                            args = { 'Sonoran Bodycam', ('Current sound level is %s'):format((soundLevel)) }
                        })
                    end
                end)
                RegisterNetEvent('SonoranCAD::bodycam::ToggleAnimation', function()
                    if doAnimation then
                        doAnimation = false
                    else
                        doAnimation = true
                    end
                    TriggerEvent('chat:addMessage',
                        { args = { 'Sonoran Bodycam', ('Animations set to %s'):format(doAnimation) } })
                end)
                RegisterNetEvent('SonoranCAD::bodycam::ToggleOverlay', function()
                    if showOverlay then
                        showOverlay = false
                    else
                        showOverlay = true
                    end
                    if bodyCamDisplayOn then
                        SendNUIMessage({
                            type = 'bodycamOverlay',
                            visible = showOverlay,
                            location = pluginConfig.overlayLocation
                        })
                    end
                    TriggerEvent('chat:addMessage',
                        { args = { 'Sonoran Bodycam', ('Overlay set to %s'):format(showOverlay) } })
                end)
            end)
        end
    end)
end)
